---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-fund-valuation
  labels:
    app: stock-fund-valuation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-fund-valuation
  template:
    metadata:
      labels:
        app: stock-fund-valuation
    spec:
      containers:
      - name: stock-fund-valuation
        image: stock-fund-valuation:latest
        ports:
        - containerPort: 8080
