---
apiVersion: v1
kind: Service
metadata:
  name: stock-fund-valuation
spec:
  type: ClusterIP
  selector:
    app: stock-fund-valuation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
